app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/SimpleOAuth2
  command: bash -c "make clean -C SimpleOAuth2 && make -C SimpleOAuth2 && SimpleOAuth2/.build/debug/SimpleOAuth2"
